### ISSUE TITLE
2.0.0 版本遇到问题: Unhandled Rejection (TypeError): Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by wangzhongchunongithub** [umijs/umi-plugin-antd-icon-config#6]
- 插件版本: 2.0.0 
- route的icon加载时报错 **Unhandled Rejection (TypeError): Cannot read property 'forEach' of undefined**
```
formatter
node_modules/umi-plugin-antd-icon-config/lib/app.js:19
 16 | }
  17 | 
  18 | function formatter(data) {
> 19 |   data.forEach(function () {
  20 |     var item = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {
  21 |       path: '/'
  22 |     };
```
```
patchRoutes
node_modules/umi-plugin-antd-icon-config/lib/app.js:49
  46 | 
  47 | function patchRoutes(_ref) {
  48 |   var routes = _ref.routes;
> 49 |   formatter(routes);
  50 | }
```
```
(anonymous function)
node_modules/umi/lib/runtimePlugin.js:110
  107 |   (0, _assert.default)(Array.isArray(item), "item must be Array");
  108 |   item.forEach(function (fn) {
  109 |     (0, _assert.default)(typeof fn === 'function', "applied item must be function");
> 110 |     fn(initialValue);
  111 |   });
  112 | } // shadow merge
  113 | 
```

### 对比更新历史， 应该是与patchRoutes的修改相关。

**Comment by sorrycc** [comment]
复现步骤？

**Comment by xiejesses** [comment]
遇到同样的问题

**Comment by wangzhongchunongithub** [comment]
> 复现步骤？

- 1.ant design pro的项目, package.json配置umi-plugin-antd-icon-config版本为2.0.0. 并安装.
- 2.配置路由, 设置一个路由的icon为home
- 3.npm start，打开页面就报issue所列的错误.

- 但安装umi-plugin-antd-icon-config较低版本如 1.0.3就不会出错

**Comment by erichDuanET** [comment]
The same problem.
I will try to roll back to  1.0.3, if it can work, hope it can work.

**Comment by sorrycc** [comment]
* umi 2 用 1.x
* umi 3 用 2.x

**Comment by UchihaItachi6** [comment]
在data.forEach前面加个判断，  
function formatter(data) {
  if(!data){
    return;
  }
  data.forEach(function () {
    var item = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {
      path: '/'
    };

**Comment by shuai4983958** [comment]
umi 2 用 1.x
umi 3 用 2.x. 解决方案是对的 ，不报错，但是图标还是字母，无法渲染出来
