### ISSUE TITLE
umijs的插件配置格式问题

### ISSUE THREAD

**Issue by lincolon** [umijs/umi-plugin-antd-icon-config#7]
按照文档配置config/config.ts，plugins: [['umi-plugin-antd-icon-config', {}]]，提示TypeError: Path must be a string.是怎么回事呢？直接配置plugins:['umi-plugin-antd-icon-config']，又提示plugin umi-plugin-antd-icon-config is already registered by /Users/lincolon/Documents/umiJs/node_modules/umi-plugin-antd-icon-config/lib/index.js, plugin from /Users/lincolon/Documents/umiJs/node_modules/umi-plugin-antd-icon-config/lib/index.js register failed.而且umijs的文档plugins参数类型也是Array<String>

**Comment by sorrycc** [comment]
umi 3 的 plugins 配置是 `string[]`。

**Comment by lijx2018github** [comment]
解决了吗请问

**Comment by zguiyang** [comment]
楼主解决了吗？
