### ISSUE TITLE
umi3.0使用问题，无法生效

### ISSUE THREAD

**Issue by Picsong** [umijs/umi-plugin-antd-icon-config#8]
按照文档复制到.umirc.ts中构建时提示路径必须是字符串，看了文档要求string[],改为plugins: ['umi-plugin-antd-icon-config'],后提示重复注册，在umi3.0中自动注册了，但是一直没有效果

**Comment by Merryy99** [comment]
> 按照文档复制到.umirc.ts中构建时提示路径必须是字符串，看了文档要求string[],改为plugins: ['umi-plugin-antd-icon-config'],后提示重复注册，在umi3.0中自动注册了，但是一直没有效果

我也不生效；我是这样写的：
const plugins = [
  [
    'umi-plugin-react',
    {
      antd: true,
      ......
    },
    'umi-plugin-antd-icon-config', {}
  ],
];

**Comment by carlchou** [comment]
一样问题
Error: plugin umi-plugin-antd-icon-config is already registered by /node_modules/umi-plugin-antd-icon-config/lib/index.js, plugin from /node_modules/umi-plugin-antd-icon-config/lib/index.js register failed.

**Comment by zhfish** [comment]
+1 ,在umi3里，不生效,表现有2
1. console里提示兼容性warning
2. 在umi2里能显示10个图标，在umi3只能显示2个

**Comment by gwsbhqt** [comment]
umi3+antd pro不生效+1。
按文档说明配置umirc.js：plugins: [['umi-plugin-antd-icon-config', {}]]会提示需要字符串，
如果配置成plugins: ['umi-plugin-antd-icon-config']会提示已经被自动引入，
如果不配置umirc.js，使用umi plugin list确实能看到umi-plugin-antd-icon-config已经被引入，但是不生效
dist\vendors~t__plugin-layout__Layout.d335f80c.async.js里还是依旧全量导入antd pro icons
