### ISSUE TITLE
能否缩减打包后的体积？

### ISSUE THREAD

**Issue by lhzbxx** [umijs/umi-plugin-antd-icon-config#9]
我看源码上默认引入了所有的 icon 包，导致打包后的体积 gzip 后还多了 150KB，能否有办法缩减打包体积？

**Comment by chenshuai2144** [comment]
能，这周会修掉

**Comment by chenshuai2144** [comment]
look here https://github.com/umijs/umi-plugin-antd-icon-config/pull/10
